### ISSUE TITLE
Añadir alumnos que faltan al fichero del hito 0

### ISSUE THREAD

**Issue by Neo-Stark** [JJ/CC-20-21#30]
En el fichero [0.md](https://github.com/JJ/CC-20-21/blob/master/proyectos/0.md) faltan entradas en la tabla de alumnos (entre los que me incluyo) para poder entregar el hito 0.

**Comment by JJ** [comment]
Sólo están las de los que estaban matriculados en ese momento. Simplemente añádela donde le corresponda, cuidando de no provocar ningún conflicto.
